### ISSUE TITLE
B.3.16.2000. - Reason

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#62]
Feature: [B.3.16.2000. - Reason](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.2000.%20-%20Reason.feature)

**Comment by mmcev106** [comment]
@aldefouw, after my changes in #177, this fails because the following step is not actually checking the checkbox:

```
I check the checkbox labeled "Require a 'reason' when making changes to existing records?"
```

I suspect this will require an rctf update.  Do you have any suggestions for how to go about that?  No worries if not.  I'll circle back to it once I've gone through lower hanging fruit.

**Comment by aldefouw** [comment]
@mmcev106  - Look into this.  I'll let you know what I find.

**Comment by aldefouw** [comment]
@mmcev106 - This issue should be addressed in RCTF v1.0.108 which is referenced above.  

I ran here and it definitely had some automatic improvements:

https://cloud.cypress.io/projects/pvu79o/runs/2003/specs

If you see any unintentional side effects let me know but it looks like it actually resulted in more scenarios passing versus Friday's run:
https://cloud.cypress.io/projects/pvu79o/runs/1985/specs

**Comment by mmcev106** [comment]
@aldefouw, thank you!  The checkbox selection seems to be working properly now.  Do you know if more rctf updates are required to enter text into the circled text box & click the circled link in the screenshot below?  I'm not immediately sure what syntax would be most appropriate to enter text into the textbox.  For the link, we could add support for `click on the first link` syntax.  What are your thoughts?

![image](https://github.com/user-attachments/assets/12dc008c-9b63-4eeb-9471-b57bbe99d326)

**Comment by aldefouw** [comment]
@mmcev106  - Look at this latest question now.

**Comment by mmcev106** [comment]
@aldefouw, I'm not sure I follow.  I'm still not sure what gherkin to use to enter text into the circled text box & click the circled link in the screenshot.

**Comment by aldefouw** [comment]
@mmcev106 - Sorry that should have said "Looking" rather than "Look".  I am looking at it 👍

**Comment by aldefouw** [comment]
@mmcev106  - seems to be passing now in run [2033](https://cloud.cypress.io/projects/pvu79o/runs/2033/test-results/7d13207a-fe1b-4bf2-a10d-bd0f15308e23/stdout?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FB%2FData%20Import_16%2FB.3.16.2000.%20-%20Reason.feature%22%2C%22value%22%3A%22%5B%5C%220e0b5266-3973-4844-bce2-ebededff6781%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)

Note that this depends on RCTF v1.0.112.
